### ISSUE TITLE
Choose to display actor's portrait vs token (+webp not supported issue)

### ISSUE THREAD

**Issue by 4m2c4bl3** [mcavallo/foundry-vtt-random-target#15]
Hi, I'd love it if there could be a setting to choose if the image displayed is the actor's portrait or token icon. 

Additionally, webms (used in animated tokens) just display as broken images. 
![image](https://github.com/user-attachments/assets/200ea8d0-9a88-4d04-8615-a0124e86c430)

seems if you just replace the image with this, then it works just fine:
```
<video src="file.webm" autoplay="" loop="" style="
    width: inherit;"></video>
``` 

![image](https://github.com/user-attachments/assets/0e75d7cf-f1a1-4ccb-a444-939786528f90)

**Comment by mcavallo** [comment]
Hi @4m2c4bl3, thank you for the feedback. I will take a look soon!

**Comment by mcavallo** [comment]
Hi @4m2c4bl3. I just released a [new version](https://github.com/mcavallo/foundry-vtt-random-target/releases/tag/v3.2.0) that adds support for animated tokens.

I also added a new setting to control which image gets render in the target list:
![image](https://github.com/user-attachments/assets/27a90f8b-f168-478b-bb90-ce05326de260)

Please give it a try and let me know how things look on your end. I'll leave the issue open for a few days in case you have feedback.

**Comment by 4m2c4bl3** [comment]
both new features work perfectly for me, thanks!
