### ISSUE TITLE
Won't work with one of my games (but works fine in the other) no mods enabled

### ISSUE THREAD

**Issue by fishrobe** [mcavallo/foundry-vtt-random-target#17]
![random target broken](https://github.com/user-attachments/assets/ca95b4d5-a0ca-4166-ba70-0ba40c866901)

I get this in the console when I try to use Random Target in one of my games and I can't figure out why. I tested in my other game and it still works. I tried deactivating all other mods but it still doesn't work. 

Is there a fix? I tried deleting / reimporting but it still doesn't work. 

I use it all the time :(.

**Comment by mcavallo** [comment]
Hi @fishrobe, thank you for the issue report.

Could you provide more information about the Foundry version used on each of the games? Do you have the latest version of the module installed?

**Comment by mcavallo** [comment]
@fishrobe also, is this using the PF2 system?

**Comment by fishrobe** [comment]
Yes sorry both games are pf2e 6.4.1 and foundry 12.331 (both updated to
most recent stable releases).

**Comment by mcavallo** [comment]
Hi @fishrobe, I just did some testing and I couldn't reproduce the issue in my local environment using a brand new world with the latest PF2 system with only my module installed. But in any case I released a patch that might solve the issue for you.

Please get the [latest version](https://github.com/mcavallo/foundry-vtt-random-target/releases/tag/v3.2.1) and give it a try when you have time. Let me know how things look on your end and if this helps mitigating the issue.

**Comment by fishrobe** [comment]
Whatever you did worked! Tested in both worlds and they both work normally
again. Thanks a ton for your help! Like I said, I use this module at least
5-6 times every game, depending on what's going on. Sometimes a lot more.

Thanks again!

**Comment by mcavallo** [comment]
Awesome! I'm glad everything works on your end. Thank you for reporting the issue and for using my module! 😃
