### ISSUE TITLE
[Feature Request] Add filter for token disposition

### ISSUE THREAD

**Issue by p4535992** [mcavallo/foundry-vtt-random-target#4]
Add the ability to filter target options for token placement.

Basically I would like to be able to choose only among enemies who to attack or only among friends who to heal.

The use case I am thinking of is related to the Dnd5e system, but I think it can be generalized to a multisystem context.

Typically there are three known token arrangements "Hostile", "Friendly", "Neutral".

For my use case, a module setting is enough where I insert a string separated by the separator "," of the type: `Hostile,Friendly,Neutral` from which to retrieve the dispositions present on the system, or retrieve them directly from the variable `CONST.TOKEN_DISPOSITIONS` .

**Comment by mcavallo** [comment]
Hi @p4535992 thank you for the feature request, I like the idea. I just need to come up with an elegant way to handle the growing amount of categories/filters and the many use cases.

**Comment by mcavallo** [comment]
Just so you know @p4535992 I'm already working on this, so it should make it to the module soon. I don't have a timeline because the end of the year can be a bit hectic, but I'll keep you posted.

**Comment by p4535992** [comment]
No worries take your time.

**Comment by mcavallo** [comment]
@p4535992 the new [1.3.0 release](https://github.com/mcavallo/foundry-vtt-random-target/releases/tag/v1.3.0) adds support for token disposition. You can now select what categories you want visible from the module settings. I will leave this issue open for a few more days in case you have any feedback.

**Comment by p4535992** [comment]
I'll give a test this week end. Ty for the hard work.
