### ISSUE TITLE
Please add support for v11?

### ISSUE THREAD

**Issue by dmpunks** [mcavallo/foundry-vtt-random-target#8]
This mod does not work at all.

And Foundry 11 is throwing the following warning(s):

> The module "random-target" is using "name" which is deprecated in favor of "id" module "random-target" declares media.link which is unsupported, media.url should be used

Thanks in advance

**Comment by mcavallo** [comment]
Hi @dmpunks, thank you for reaching out. I'm in the process of updating the module for v11 a new version will be out soon.

**Comment by mcavallo** [comment]
I had some moderate success with a first attempt but it seems like the old macro is no longer working and cache is proving to be a problem. @dmpunks would you mind giving it a try and reporting back?

1. Remove the old version of the module
2. Install the latest version `2.0.1`+ of the module
3. Delete the old macro from the toolbar and drag a new one from the compendium

**Comment by dmpunks** [comment]
Will do, I saw your module update just now. I'll test and report back. Thanks, @mcavallo

**Comment by dmpunks** [comment]
Looks like it's working now. Awesome work. Thank you so much, @mcavallo !

**Comment by mcavallo** [comment]
Awesome, thanks for reporting the issue and for the help testing the new release 👍
