### ISSUE TITLE
Macro doesn't work (v11)

### ISSUE THREAD

**Issue by valqueerie** [mcavallo/foundry-vtt-random-target#9]
Hello! 

Since the latest update, the macro doesn't seem to work. I've tried reinstalling the module but the problem persists. This is what shows up as the script when imported from the compendium: 

![image](https://github.com/mcavallo/foundry-vtt-random-target/assets/66767292/9b410a29-3c5b-4409-bc1a-20c4fa9a5ebc)

**Comment by mcavallo** [comment]
@valqueerie what are your Foundry and module versions?

**Comment by valqueerie** [comment]
> @valqueerie what are your Foundry and module versions?

**Foundry Version:** 11.313
**Module Version:** 2.21 

I'm also using DnD5e 2.3.1, if that makes a difference.

**Comment by mcavallo** [comment]
@valqueerie I tried to replicate the issue with exactly the same versions but I couldn't. I tried both Firefox and Chrome and in both cases I was able to use the macro normally.

Can I assume you already deleted the macro and re-imported it from the compendium?

Also, could you try opening your browser's dev tools and running `window.randomTarget.run();` in the console? There might be some error messages in there can could help triaging this issue. If you don't know how to do that [here's some help](https://balsamiq.com/support/faqs/browserconsole/).

**Comment by fishrobe** [comment]
Just wanted to chime in and say I am getting the exact same error with the new PF2e system update. (Using Vivvaldi, if that matters).  Random target version 2.21, Foundry Version 11 13.315.

**Comment by fishrobe** [comment]
Oddly I have 2 games, and it works fine with one, but not the other, even with all other modules turned off. Here's the new error I get.
![random target 2](https://github.com/mcavallo/foundry-vtt-random-target/assets/50474856/a22c9bfd-d23f-42fa-9ce4-d45aea2b810c)

**Comment by mcavallo** [comment]
@fishrobe @valqueerie I just released a [new version](https://github.com/mcavallo/foundry-vtt-random-target/releases/tag/v2.3.1) that should address the issue.

To ensure you get the latest changes please follow this steps:
1. Uninstall the module completely by removing it from your server
2. Install the latest version of the module
3. Delete the Random Target macro from your toolbar
4. Import the macro again from the Random Target macro compendium

I'll leave the issue open for a few days in case you have more feedback. Please don't hesitate to report back if things are still not working as intended.

**Comment by mcavallo** [comment]
@fishrobe awesome, please do. Thanks for taking the time to report the issue 👍
